# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Approval.Vote
email: felix@electology.org
description: > # this means to ignore newlines until "baseurl:"
  A better way to elect representatives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fsargent/approval.vote

# Build settings
markdown: kramdown
theme: uswds-jekyll
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:

  # # If defined and browserify and uglifyify are installed, the plugin will
  # # generate a bundle to define the renderJekyllPagesApiSearchResults
  # # function.
  # browserify:
  #   source: js/my-search.js
  #   target: js/my-search-bundle.js